# Generated by Django 3.2.9 on 2021-12-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('jwt_auth', '0003_alter_user_is_searching'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workout_types',
            field=models.ManyToManyField(blank=True, to='workouts.Workout'),
        ),
    ]
