# Generated by Django 3.2.9 on 2021-12-03 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allow_female',
            new_name='allowFemale',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='allow_males',
            new_name='allowMales',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='allow_non_binary',
            new_name='allowNonBinary',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_searching',
            new_name='isSearching',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='workout_types',
            new_name='workoutTypes',
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
