# Generated by Django 3.2.9 on 2021-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_searching',
            field=models.BooleanField(default=True),
        ),
    ]
