# Generated by Django 3.2.9 on 2021-12-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shout',
            old_name='created_at',
            new_name='created',
        ),
    ]
