# Generated by Django 3.2.9 on 2021-12-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotmes', '0004_spotme_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotme',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='spotme',
            old_name='searching_for',
            new_name='searchingFor',
        ),
        migrations.RenameField(
            model_name='spotme',
            old_name='workout_types',
            new_name='workoutTypes',
        ),
    ]
