# Generated by Django 3.2.9 on 2021-12-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='isRead',
        ),
    ]
